Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }
    
    public BestRestaurantsContext(DbContextOptions options) : base(options) { }
  }
}

Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
        this.Restaurants = new HashSet<Restaurant>();
    }

    public int CuisineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
}

Models/Restaurant.cs
namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Description { get; set; }
    public int CusineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }
}

Controllers/CusinesController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost] 
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h4>Add a new cuisine</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new cuisine" />
}

<p>@Html.ActionLink("Show all cuisines", "Index")</p>

Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Are you sure you want to delete this cuisine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.Display for(model => model.Name)
@using (Html.beginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to cuisines", "Index")

Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model BestRestaurants.Models.Cuisine;

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<ul></ul>
@if (Model.Restaurants.Count == 0)
{
  <p>No restaurants found</p>
}

@foreach (Restaurant restaurant in @Model.Restaurants)
{
    <li>@restaurant.Name</li>
}

<p>@Html.ActionLink("Back to Cuisines", "Index")</p>
@* <p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p> *@
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>

Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Cuisine>

<h1>Cuisines</h1>

@if (@Model.Count == 0)
{
  <h3>No cuisines have been added, yet.</h3>
}

@foreach (BestRestaurants.Models.Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
}

<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>The Best Restaurants in PDX!</h1>
<p>@Html.ActionLink("See all cuisines", "Index", "Cuisines")</p>
<p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Best Restaurants PDX</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>